### PR TITLE
[BD-26] Timer bar on non-sequence pages

### PR DESCRIPTION
**Pull request by UvgenGen**
Change URL for ProctoredExamAttempt API

**Jira**: [EDUCATOR-5857](https://openedx.atlassian.net/browse/EDUCATOR-5857)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @UvgenGen! I've created [BLENDED-899](https://openedx.atlassian.net/browse/BLENDED-899) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Review by idegtiarov — APPROVED** [review]
LGTM so far

**Comment by Zacharis278** [comment]
It looks like we are actually hitting this endpoint outside of an exam sequence, meaning this endpoint is technically in use in production. Can we make this backward compatible with the old URL format (temporarily at least, it doesn't have to be pretty)

**Comment by UvgenGen** [comment]
We can leave the old URL that will use the same view, and update the view to use the content id from the query or from the URL parameter. Is this solution okay?

**Comment by Zacharis278** [comment]
yeah that seems like the best solution to me. We can remove that extra URL once the frontend is deployed.

**Review by idegtiarov — APPROVED** [review]
LGTM

**Review by Zacharis278 — APPROVED** [review]
looks good thanks!

**Pull request merged**
