### PR TITLE
Changelog Pilot

### PR DESCRIPTION
**Pull request by Zacharis278**
@edx/masters-devs-cosmonauts 

**Description:**

This is PR is a proposal to alter our process for tracking changes to the edx-proctoring library. We will maintain an explicit change log for each release of the library. It is the responsibility of engineers to maintain this file. As an effort to hold ourselves accountable I've added a PR template to serve as a reminder of this process.

**JIRA:**

(not applicable)

**Pre-Merge Checklist:**

- [x] Updated the version number in `edx_proctoring/__init__.py` and `package.json` if these changes are to be released.
- [x] Described your changes in `CHANGELOG.rst`
- [x] Confirmed Github reports all automated tests/checks are passing.
- [x] Approved by at least one additional reviewer.

**Post-Merge:**

- [ ] Create a tag matching the new version number.

### CODE REVIEW

**Review by alangsto — APPROVED** [review]
LGTM!

**Review by schenedx — APPROVED** [review]
👍 Thank you for doing this work!

**Review by matthugs — APPROVED** [review]

**Review by idegtiarov — APPROVED** [review]
LGTM!

**Comment by nedbat** [comment]
I am a huge fan of this :)

**Pull request merged**
