### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/solutions-team: I'm marking this repo as yours.

**Comment by smagoun** [comment]
Solutions recently transitioned this repo to the T&L team. Not sure what their github handle is, I didn't see an obvious one.

**Comment by cpennington** [comment]
I've been tagging their repos with `edx/teaching-and-learning`. I'll change this one (I'll be looking to get a github handle created once I have the repos tagged).

**Comment by cpennington** [comment]
@edx/teaching-and-learning: I've tagged your team as the owner of this repo. Ok to merge?

**Comment by andy-armstrong** [comment]
👍

**Pull request merged**
