### PR TITLE
Upgrade django-rest-framework to v3.1

### PR DESCRIPTION
**Pull request by wedaly**
Upgrade Django Rest Framework to v3.1 in preparation for the Django 1.8 upgrade.

This is a WIP PR and won't be merged until all of edx-platform and its dependencies have been upgraded to DRF 3.1.

### CODE REVIEW

**Comment by chrisndodge** [comment]
Interesting that we lost coverage with this change.  Does the upgrade of DRF change the behavior or needing to define a "from_native()"? If so, then we should remove that code...

**Comment by chrisndodge** [comment]
@wedaly as this runs in-proc with LMS, I don't think I can pull in these changes until LMS upgrade DRF. Or is that change you made in the serializers backwards compatible with v2.x of DRF?

**Comment by wedaly** [comment]
@chrisndodge I'm working on the upgrade to edx-platform this week.  I'm planning to wait until I have all the pieces ready (ORA, submissions, val, proctoring, and edx-platform) before I ask for code reviews.  I'll send out an email tomorrow with more details.

**Comment by chrisndodge** [comment]
Closing, to re-open against current RC branch

**Pull request closed without merging**
