### PR TITLE
PHX-141 added the timer accessibility issue.

### PR DESCRIPTION
**Pull request by muhhshoaib**
@chrisndodge Kindly review the changes for the PHX-141

### CODE REVIEW

**Comment by chrisndodge** [comment]
@clrux here are the BackbonJS changes.

**Comment by clrux** [comment]
With my very limited Backbone knowledge, this seems to be okay. So long as:

* the text within the ARIA container is updated, and
* the updates are announced

Will I be able to test this at some point on a sandbox?

**Comment by chrisndodge** [comment]
@clrux thanks, yes, I will refresh our sandbox (probably on 10/10)

**Comment by chrisndodge** [comment]
@muhhshoaib I did some review and testing and I made some changes myself. I hope you don't mind - because we kinda need this merged in today so I can start making release branches tomorrow and refresh our sandbox.

**Pull request merged**
