### PR TITLE
fix the bug where hitting software secure callback URL second time  w…

### PR DESCRIPTION
**Pull request by ibrahimahmed443**
…ould revert the state back to 'ready to start' from 'started'

### CODE REVIEW

**Comment by chrisndodge** [comment]
@afzaledx can someone do initial review? Thanks

FYI @douglashall

**Comment by muhhshoaib** [comment]
@ibrahimahmed443 write the test case to make sure the status won't change to `ready_to_start` when hitting the url second time.

**Comment by muhhshoaib** [comment]
:+1:  LGTM

**Comment by chrisndodge** [comment]
squashing commits and then merging...

**Pull request merged**
