### PR TITLE
Check and Final Check are being replaced in Capa with Submit.

### PR DESCRIPTION
**Pull request by staubina**
@cahrens @alisan617 @sstack22 

This PR contains updates to change from Check and Final Check to Submit.

### Description
 
[TNL-5055](https://openedx.atlassian.net/browse/TNL-5055)

### Testing
- [x] safecommit shows 0 violations
- [x] Unit, integration, acceptance tests as appropriate

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @cahrens 
- [x] Code review: @alisan617 
- [x] Doc Review: @catong 
- [x] Product review: @sstack22 

### Post-review
- [x] Squash commits

### CODE REVIEW

**Comment by alisan617** [comment]
@staubina there is one more instance in proctored-exam-status.underscore

**Comment by staubina** [comment]
@alisan617 Thank you, I will get that one now.

**Comment by staubina** [comment]
@alisan617 That file is in edx-platform.  I will have another PR soon.

**Comment by staubina** [comment]
Please review the changes here when you have a chance.  I am going to wait to merge until TNL-4880 feature branch merges.

https://github.com/edx/edx-platform/pull/13052

**Comment by cahrens** [comment]
👍

**Comment by staubina** [comment]
@catong Please take a look at these changes real quick also.  Mainly an FYI.

**Comment by catong** [comment]
👍 Thanks @staubina

**Comment by sstack22** [comment]
@staubina , @catong - can we find out what the button text is for the timed exam/final exam? We may want to tweak the instructions so we don't say submit twice "Make sure that you have selected "Submit" for each problem before you submit your exam."

**Comment by sstack22** [comment]
@staubina , @catong  - scratch that, looks like you had this discussion and made updates (not shown here) on  https://github.com/edx/edx-platform/pull/13484

**Pull request merged**
