### PR TITLE
SOL-1221

### PR DESCRIPTION
**Pull request by hasnain-naveed**

### CODE REVIEW

**Comment by chrisndodge** [comment]
This LGTM. @afzaledx or @muhhshoaib can one of you also sign off on it?

**Comment by afzaledx** [comment]
:+1:

**Comment by afzaledx** [comment]
Having a bit of trouble on the edx-platform branch of this story with the bokchoy tests. Probably better to hold off merging this before the edx-platorm branch is merged. If we merge, it wont break anything but we might see some styling glitches that are there in the platform branch.

**Comment by chrisndodge** [comment]
@afzaledx @muhhshoaib @hasnain-naveed I'll pick this up and see if I can wrap it up today. Not clear what's going on with the UI tests.

**Pull request merged**
