### PR TITLE
[BD-26] Add API endpoint to fetch exam review policy and extend current API

### PR DESCRIPTION
**Pull request by ViktorRusakov**
**Description:**

This PR adds new API endpoint which provides exam review policy for specific exam and also extends current API in various ways. Exam attempt API is extended to return additional data about proctored exams and to check if user has satisfied prerequisites before taking proctored exam, while proctoring settings API is extended to return additional data about proctoring provider. 

Usage case for all of the above is to provide required data for the learning app MFE.

**JIRA:**

[EDUCATOR-5808](https://openedx.atlassian.net/browse/EDUCATOR-5808)
[EDUCATOR-5813](https://openedx.atlassian.net/browse/EDUCATOR-5813)
[EDUCATOR-5816](https://openedx.atlassian.net/browse/EDUCATOR-5816)

**Pre-Merge Checklist:**

- [ ] Updated the version number in `edx_proctoring/__init__.py` and `package.json` if these changes are to be released.
- [x] Described your changes in `CHANGELOG.rst`
- [x] Confirmed Github reports all automated tests/checks are passing.
- [x] Approved by at least one additional reviewer.

**Post-Merge:**

- [ ] Create a tag matching the new version number.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ViktorRusakov! I've created [BLENDED-875](https://openedx.atlassian.net/browse/BLENDED-875) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


When this pull request is ready, tag your edX technical lead.

**Comment by ViktorRusakov** [comment]
@Zacharis278 I have combined 4 of my other PRs into this one, hope this is okay, the changelog might look big but most of it are updates to tests. The actual changes are small new API endpoint and extending existing APIs to return some additional data.

**Review by Zacharis278 — APPROVED** [review]
just some minor comments, otherwise LGTM

**Comment by Zacharis278** [comment]
tagging @edx/masters-devs-cosmonauts for visibility

**Review by idegtiarov — APPROVED** [review]
LGTM

**Pull request merged**
