### PR TITLE
change proctoring eligibility to be true unless we explicitly failed …

### PR DESCRIPTION
**Pull request by chrisndodge**
…a icrv

### CODE REVIEW

**Comment by chrisndodge** [comment]
@afzaledx @muhhshoaib can you take a look at this when you get a chance. Basically I think we need to change two bits of logic regarding when we show the proctoring screen:

- We always show proctoring as long as there is no failure in the ICRV processing. Current implementation is that all ICRV needs to be passed before a proctoring can occur. But this is incorrect because an ICRV can happen after the first proctoring: e.g. ICRV1, Proctoring1, ICRV2, Proctoring2

- Also, when we fail/decline on proctoring exam, the business logic is supposed to be that all other proctored exams not yet started should be also marked as declined, so that the user does not get the option to choose proctoring

I'd like to get this change into next week's release so that we can have the correct business logic in production.

**Comment by afzaledx** [comment]
@chrisndodge, Since you made a ProctoredExamStudentAttemptStatus class, it made sense to use it everywhere we were checking the status to be in a list or not. Made the changes and have created a PR https://github.com/edx/edx-proctoring/pull/97. Otherwise :+1:

**Comment by afzaledx** [comment]
@chrisndodge, Since you made a ProctoredExamStudentAttemptStatus class, it made sense to use it everywhere we were checking the status to be in a list or not. Made the changes and have created a PR https://github.com/edx/edx-proctoring/pull/98. Otherwise :+1:

**Comment by chrisndodge** [comment]
I want to do a manual check on this PR before I merge it.

**Comment by chrisndodge** [comment]
OK, I did a manual check on localdev with the following gating order:

ICRV1, Proctoring1, ICRV2, Proctoring2

Now we only remove the proctoring option when the user explicitly fails ICRV1/2, however if it is in a pending state, the proctoring option will still be available.

**Pull request merged**
