### PR TITLE
Upgrade django to 1.8.

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
TNL-3304

### CODE REVIEW

**Comment by chrisndodge** [comment]
@muzaffaryousaf when does this need to get merged in? What is the current schedule to get edx-platform onto Django 1.8?

**Comment by muzaffaryousaf** [comment]
@chrisndodge We have upgraded all the sub repos to use 1.8 except this one. We will merge these when we are done with edx-platform which is in progress right now. Can't say anything about the exact schedule.

**Comment by chrisndodge** [comment]
Thanks, there are a lot of fundamental failures happening on the Travis build. We're you able to run the unit tests locally?

**Comment by chrisndodge** [comment]
Also we have 2 more migrations on our release candidate. Those will get merged to master on Thursday, once the release out the door, so there will have to be some additional work on this.

**Comment by muzaffaryousaf** [comment]
@chrisndodge Yes i was able to run the tests locally and made the fix for new migrations. I will take care of this in morning. 
Thanks.

**Comment by muzaffaryousaf** [comment]
Will tag you once i got green build.

**Comment by muzaffaryousaf** [comment]
Quality task is failing due to pep8 warnings.

**Comment by chrisndodge** [comment]
@muzaffaryousaf what is the schedule to go live with Django 1.8? Our master has changed a lot since this PR was made and there are new migrations. Is there a plan to reconcile the diffs? You can talk with @afzaledx and @muhhshoaib if you need some assistance.

FYI, @doctoryes @smagoun

**Comment by nedbat** [comment]
@chrisndodge: @macdiesel is the head guy on Django 1.8.  We will be taking into account all of the migrations, and we will update this PR to the latest master-referenced commit before doing the big upgrade.

**Comment by chrisndodge** [comment]
@macdiesel can we sync up about Django 1.8 upgrade? I think this build is failing because of PEP8, which is simple, but I don't think this PR is up to date with all changes since late Sept.

**Comment by chrisndodge** [comment]
@macdiesel @muzaffaryousaf I fixed pylint errors and rebased and resolved conflicts (which were just in setup.py versioning). HOWEVER, you will need to update the hash you are using in requirements/edx/github.txt to be 0890c3c

**Comment by chrisndodge** [comment]
OK, we have a broken test. It's new code and it's not following the update pattern. I should be able to resolve this.

**Comment by muzaffaryousaf** [comment]
@chrisndodge Thanks for fixing the pylint issues. Also, i've rebased this PR last week. I don't know what makes you to think about the last sep. Was there missing code from this PR ?

**Pull request merged**
