### PR TITLE
SOL-1222

### PR DESCRIPTION
**Pull request by muhhshoaib**
Updated permissions in edx-proctoring so that course staff members can view list of attempts and allowances

### CODE REVIEW

**Comment by chrisndodge** [comment]
@muhhshoaib can you pick an initial reviewer on this?

**Comment by muhhshoaib** [comment]
@afzaledx can you do an initial review?

**Comment by afzaledx** [comment]
:+1:

**Comment by muhhshoaib** [comment]
@chrisndodge @afzaledx has passed the initial review. The corresponding edx-platform PR for this story has been merged.

**Comment by chrisndodge** [comment]
@muhhshoaib can you squash commits and merge?

**Comment by chrisndodge** [comment]
Hey, looking at this. THis looks ready to go, but I don't think there's a PR for the addition of this new is_course_staff() method in the services.py file in edx-platform/lms/djangoapps/instructor....

Right now I thin this PR along will cause an unhandled exception when it tries to call into the LMS to check permissions.

Did I miss something or is there still an outstanding PR to be submitted on edx-platform?

**Comment by muhhshoaib** [comment]
@chrisndodge here is the link of the corresponding edx-platform PR (https://github.com/edx/edx-platform/pull/9825) that has been into `cdodge/timed-exams` but i cannot find any related changes in t `cdodge/timed-exams` and i am going to create a new PR in edx-platform for SOL-1222 against `cdodge/timed-exams`and merge it in. I think force push has caused this issue.

**Comment by muhhshoaib** [comment]
created a new PR https://github.com/edx/edx-platform/pull/10006. I will merge this into `cdodge/timed-exams` once the test passes.

**Comment by chrisndodge** [comment]
@muhhshoaib thanks, and you are probably right about a force push (I had rebased). However, that does get me a bit concerned that I might have dropped something else....

Thanks for the new PR

**Pull request merged**
