### PR TITLE
Initial Arabic locale po file

### PR DESCRIPTION
**Pull request by firasalkafri**

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @firasalkafri! I've created [OSPR-1565](https://openedx.atlassian.net/browse/OSPR-1565) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/edx-proctoring/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@firasalkafri Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

**Comment by firasalkafri** [comment]
@gsong [https://github.com/edx/edx-platform/files/575789/individual-contributor-agreement.pdf](url)

**Comment by sstack22** [comment]
@firasalkafri - would you mind clarifying the impact of this pull request?

**Comment by gsong** [comment]
@nedbat Should this be translated via Transifex?

@sstack22 These are just translation for labels and messages within this component.

**Comment by nedbat** [comment]
@gsong @firasalkafri I don't know how this repo is managing their translations. Ideally, it would be Transifex.

**Comment by gsong** [comment]
@sstack22 Anyone on the TNL team able to take a quick look at this to determine if we want to do translations this way in this repo?

@firasalkafri Would you be able to rebase your changes on top of current `master`?

**Comment by cahrens** [comment]
@andy-armstrong How are translations done now in proctoring? Does it make sense to merge some variation of this PR?

**Comment by andy-armstrong** [comment]
@firasalkafri Thanks for taking the time to make this PR. We have recently switched the edx-proctoring repo over to using Transifex, so given that I'm going to close this PR.

The way to contribute translations now is to upload them to Transifex:

https://www.transifex.com/open-edx/edx-platform/edx-proctoring/
https://www.transifex.com/open-edx/edx-platform/edx-proctoring-js/

Interestingly, our Arabic translation coverage is already at 100%, so somebody has taken the time to do this already. Please feel free to join the project (if you haven't already) and help us to improve the quality.

**Pull request closed without merging**
