### PR TITLE
PHX-213 / remove the "expire" status in exam attempt

### PR DESCRIPTION
**Pull request by hasnain-naveed**

### CODE REVIEW

**Comment by afzaledx** [comment]
:+1:

**Comment by chrisndodge** [comment]
rebased against Django 1.8 merge

**Comment by chrisndodge** [comment]
Tried it locally. Thx.

+1

**Comment by chrisndodge** [comment]
Note, I separated out an expired.html template for timed_exams as there is messaging regarding credit eligibility in the proctored exam copy of that template.

**Pull request merged**
